# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-26 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='quote',
        ),
        migrations.AddField(
            model_name='like',
            name='quote',
            field=models.ManyToManyField(related_name='liked', to='quote_app.Quote'),
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ManyToManyField(related_name='likes', to='quote_app.User'),
        ),
    ]
