# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-26 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote_app', '0002_auto_20180926_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='quote',
            field=models.ManyToManyField(related_name='liked_quotes', to='quote_app.Quote'),
        ),
    ]
